package deadconst_test

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/1qh/lintmax-go/internal/deadconst"
)

const (
	fixturePkg = "package fixture\n"
	groupFile  = "group.go"
)

func writeMod(t *testing.T) string {
	t.Helper()
	dir := t.TempDir()
	files := map[string]string{
		"go.mod": "module deadconstfixture\n\ngo 1.23\n",
		groupFile: fixturePkg + "const (\nused = 1\ndead = 2\n)\n" +
			"var Reader = used\n",
		"iota.go":     fixturePkg + "const (\nfirst = iota\nsecond\n)\nvar Position = first\n",
		"export.go":   fixturePkg + "const Exported = 3\n",
		"testread.go": fixturePkg + "const testOnly = 4\n",
		"reader_test.go": fixturePkg + "import \"testing\"\n" +
			"const testDeclaration = 5\n" +
			"func TestReader(t *testing.T) { if testOnly == 0 { t.Fatal(testOnly) } }\n",
		"generated.go": "// Code generated by fixture. DO NOT EDIT.\npackage fixture\nconst generated = 6\n",
		"local.go":     fixturePkg + "const _ = 7\nfunc Local() { const local = 8 }\n",
	}
	for name, body := range files {
		err := os.WriteFile(filepath.Join(dir, name), []byte(body), 0o600)
		if err != nil {
			t.Fatal(err)
		}
	}
	return dir
}

func TestScan(t *testing.T) {
	t.Parallel()
	dir := writeMod(t)
	issues, err := deadconst.Scan(t.Context(), dir)
	if err != nil {
		t.Fatal(err)
	}
	if len(issues) != 1 {
		t.Fatalf("want only the dead member of the non-iota group, got %+v", issues)
	}
	want := deadconst.Issue{
		Pos:  filepath.Join(dir, groupFile) + ":4:1",
		Name: "dead",
		Pkg:  "deadconstfixture",
	}
	if issues[0] != want {
		t.Errorf("Scan() = %+v, want %+v", issues[0], want)
	}
	wantText := want.Pos + ": dead is declared and never read\n"
	if got := deadconst.Format(issues); got != wantText {
		t.Errorf("Format() = %q, want %q", got, wantText)
	}
}

func TestFormatEmpty(t *testing.T) {
	t.Parallel()
	if got := deadconst.Format(nil); got != "" {
		t.Errorf("Format(nil) = %q, want empty output", got)
	}
}
