package repo

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

const (
	lineWidth   = 123
	indentWidth = 2
	dprintBin   = "dprint"
	typosBin    = "typos"
	dprintFile  = "dprint.json"
	typosFile   = "typos.toml"
	configFlag  = "--config"
	configMode  = 0o600
)

func minified() []string {
	return []string{"*.min.js", "*.min.css", "*.min.mjs", "*.min.map", "*.lock"}
}

func unauthored() []string {
	return []string{"testdata", "node_modules", "vendor", "dist", "target"}
}

func quoted(values []string) []string {
	out := make([]string, 0, len(values))
	for _, value := range values {
		out = append(out, "\""+value+"\"")
	}
	return out
}

func excludes() []string {
	return append([]string{
		"**/.git",
		"**/node_modules",
		"**/vendor",
		"**/testdata",
		"**/dist",
		"**/target",
		"**/go.sum",
	}, prefixed(minified())...)
}

func prefixed(values []string) []string {
	out := make([]string, 0, len(values))
	for _, value := range values {
		out = append(out, "**/"+value)
	}
	return out
}

func Config(ctx context.Context, dir string) (string, error) {
	body, err := json.MarshalIndent(map[string]any{
		"lineWidth":   lineWidth,
		"indentWidth": indentWidth,
		"useTabs":     false,
		"newLineKind": "lf",
		"includes":    []string{"**/*"},
		"excludes":    excludes(),
		"plugins":     Latest(ctx, Seed()),
	}, "", "  ")
	if err != nil {
		return "", fmt.Errorf("encoding the dprint config: %w", err)
	}
	dprintErr := os.WriteFile(filepath.Join(dir, dprintFile), body, configMode)
	if dprintErr != nil {
		return "", fmt.Errorf("writing the dprint config: %w", dprintErr)
	}
	typos := "[default]\ncheck-filename = true\ncheck-file = true\n" +
		"[files]\nextend-exclude = [" + strings.Join(quoted(append(minified(), unauthored()...)), ", ") + "]\n"
	typosErr := os.WriteFile(filepath.Join(dir, typosFile), []byte(typos), configMode)
	if typosErr != nil {
		return "", fmt.Errorf("writing the typos config: %w", typosErr)
	}
	return dir, nil
}

// A project may supply the DATA a speller needs to be correct about it — its own domain vocabulary —
// through the tool's OWN config file rather than a lintmax-specific one, so there is no second home
// for a fact `typos` already owns. It supplies data only: no rule can be turned off from there,
// because the file replaces the word list rather than the check.
func typosConfig(root, cfg string) string {
	own := filepath.Join(root, typosFile)
	_, err := os.Stat(own)
	if err != nil {
		return filepath.Join(cfg, typosFile)
	}
	return own
}

func Gate(ctx context.Context, root string, fix bool) []string {
	dir, err := os.MkdirTemp("", "lintmax-go-repo-")
	if err != nil {
		return []string{"repo config: " + err.Error()}
	}
	defer func() { _ = os.RemoveAll(dir) }() //nolint:errcheck // a temp dir that outlives the run is harmless
	cfg, cfgErr := Config(ctx, dir)
	if cfgErr != nil {
		return []string{"repo config: " + cfgErr.Error()}
	}
	action := "check"
	if fix {
		action = "fmt"
	}
	specs := []struct {
		name string
		args []string
	}{
		{name: dprintBin, args: []string{action, configFlag, filepath.Join(cfg, dprintFile)}},
		{name: typosBin, args: []string{configFlag, typosConfig(root, cfg), root}},
	}
	var notes []string
	for _, spec := range specs {
		notes = append(notes, judge(ctx, root, spec.name, spec.args)...)
	}
	return notes
}

func judge(ctx context.Context, root, name string, args []string) []string {
	_, lookErr := exec.LookPath(name)
	if lookErr != nil {
		return []string{name + ": not installed, so every non-Go file went unchecked"}
	}
	//nolint:gosec // fixed tool name, and every argument is generated by this package
	cmd := exec.CommandContext(ctx, name, args...)
	cmd.Dir = root
	out, runErr := cmd.CombinedOutput()
	if runErr == nil {
		return nil
	}
	return []string{name + ":\n" + strings.TrimRight(string(out), "\n")}
}
