//nolint:testpackage // reason: exercises unexported isGenerated
package run

import (
	"os"
	"path/filepath"
	"testing"
)

func TestIsGeneratedDetectsCanonicalHeader(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	gen := filepath.Join(dir, "models.go")
	genErr := os.WriteFile(gen, []byte("// Code generated by sqlc. DO NOT EDIT.\npackage x\n"), 0o600)
	if genErr != nil {
		t.Fatalf("write gen: %v", genErr)
	}
	hand := filepath.Join(dir, "hand.go")
	handErr := os.WriteFile(hand, []byte("package x\n\nvar X = 1\n"), 0o600)
	if handErr != nil {
		t.Fatalf("write hand: %v", handErr)
	}
	if !isGenerated(gen) {
		t.Fatal("canonical generated header must be detected")
	}
	if isGenerated(hand) {
		t.Fatal("hand-written file must not be flagged generated")
	}
	if isGenerated(filepath.Join(dir, "nope.go")) {
		t.Fatal("missing file must not be flagged generated")
	}
}
